"""initial migration

Revision ID: c8a462adef26
Revises: 
Create Date: 2024-06-28 13:47:12.161581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a462adef26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Airplane',
    sa.Column('AirplaneID', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('economy_seats', sa.Integer(), nullable=False),
    sa.Column('business_seats', sa.Integer(), nullable=False),
    sa.Column('first_class_seats', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('AirplaneID')
    )
    op.create_table('Airport',
    sa.Column('AirportID', sa.Integer(), nullable=False),
    sa.Column('airport_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('AirportID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Flight',
    sa.Column('FlightID', sa.Integer(), nullable=False),
    sa.Column('Flight_Number', sa.Integer(), nullable=True),
    sa.Column('Departure_Airport', sa.String(), nullable=False),
    sa.Column('Arrival_Airport', sa.String(), nullable=False),
    sa.Column('Departure_Date_time', sa.DateTime(), nullable=True),
    sa.Column('Arrival_Date_time', sa.DateTime(), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('AirPlaneID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AirPlaneID'], ['Airplane.AirplaneID'], ),
    sa.PrimaryKeyConstraint('FlightID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Flight')
    op.drop_table('user')
    op.drop_table('Airport')
    op.drop_table('Airplane')
    # ### end Alembic commands ###
